spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.application.name=microservicio-java
server.port=${PORT:8080}

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

springdoc.swagger-ui.path=/docs